module Pdfs
  class PayrollPdf
    FONT_REGULAR = Rails.root.join(
      "app/assets/fonts/DejaVuSans.ttf"
    )

    FONT_BOLD = Rails.root.join(
      "app/assets/fonts/DejaVuSans-Bold.ttf"
    )

    def initialize(payroll)
      @payroll = payroll
      @user = payroll.user
      @profile = @user.employee_profile
    end

    def render
      Prawn::Document.new(page_size: "A4") do |pdf|
        pdf.font_families.update(
          "DejaVuSans" => {
            normal: FONT_REGULAR,
            bold:   FONT_BOLD
          }
        )
        pdf.font("DejaVuSans")

        pdf.text "HRLite Payslip", size: 20, style: :bold
        pdf.move_down 10
        pdf.text "Month: #{@payroll.month.strftime("%B %Y")}", size: 12

        pdf.move_down 15
        pdf.text "Employee Details", style: :bold
        pdf.text "Name: #{@profile.first_name} #{@profile.last_name}"
        pdf.text "Emp ID: #{@profile.emp_id}"
        pdf.text "Designation: #{@profile.designation}"

        pdf.move_down 15
        pdf.text "Attendance Summary", style: :bold
        pdf.text "Paid Days: #{@payroll.paid_days}"
        pdf.text "Unpaid Days: #{@payroll.unpaid_days}"
        pdf.text "Payable Days: #{@payroll.payable_days}"

        pdf.move_down 15
        pdf.text "Salary Summary", style: :bold
        pdf.text "Gross (Monthly): ₹ #{@payroll.gross_monthly || @payroll.gross_salary}"
        pdf.text "Gross (Payable): ₹ #{@payroll.gross_payable || @payroll.gross_salary}"
        pdf.text "Deductions: ₹ #{@payroll.deductions_payable || 0}"
        pdf.text "Net Salary: ₹ #{@payroll.net_payable || @payroll.net_salary}", style: :bold

        pdf.move_down 20
        pdf.text "Generated by HRLite", size: 10, align: :right
      end.render
    end
  end
end
